<a href="https://colab.research.google.com/github/bryted/randomactivities/blob/main/Autodebitp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import glob

In [ ]:
#read maximus file
path =r"/content/drive/MyDrive/content/"
filenames = glob.glob(path + "/*.xlsx")
df_mp = main_dataframe = pd.DataFrame(pd.read_excel(filenames[0]))

In [ ]:
df_mp = pd.read_excel('maximus-payment_export-1646122734456.xlsx')

In [ ]:
df = pd.read_excel('MerchantTransactionHistoryAgentWise_01_02_2022_to_28_02_2022.xlsx')

In [ ]:
df

In [ ]:
df_mp1 = df_mp[['tranid','source']] #picking out only two columns from main data
df_mp1.rename(columns={'tranid': 'Merchant Ref.Code'}, inplace=True) #renaming columns for cohesion

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_mp = pd.read_excel('maximus-payment_export-1646122734456.xlsx')

In [ ]:
#this code determines the source of payments( AUTODEBIT,USSD,etc.)
dfm = pd.merge( df, df_mp1,
                      on ='Merchant Ref.Code', 
                      how ='left') 
dfm.rename(columns={'Payee Mobile': 'Mobile'}, inplace=True)#renaming columns for cohession
dfm['source'].fillna('Not Available',inplace = True)

In [ ]:
dfm

       Trans.ID             Trans.Date  ... Customer Mobile Number         source
0     118683877  28/02/2022 11:59:53PM  ...                    NaN  Not Available
1     118683866  28/02/2022 11:59:37PM  ...                    NaN  Not Available
2     118683822  28/02/2022 11:56:18PM  ...                    NaN  Not Available
3     118683817  28/02/2022 11:55:48PM  ...                    NaN  Not Available
4     118683808  28/02/2022 11:55:33PM  ...                    NaN  Not Available
...         ...                    ...  ...                    ...            ...
7330  115075760  01/02/2022 12:02:38AM  ...                    NaN      AUTODEBIT
7331  115075750  01/02/2022 12:02:08AM  ...                    NaN      AUTODEBIT
7332  115075738  01/02/2022 12:01:38AM  ...                    NaN      AUTODEBIT
7333  115075733  01/02/2022 12:01:23AM  ...                    NaN      AUTODEBIT
7334  115075709  01/02/2022 12:00:24AM  ...                    NaN      AUTODEBIT

[7335 rows x 30 columns]

In [ ]:
a = dfm.loc[((dfm['Transaction Type'] == 'Direct Debit') | (dfm['source'] == 'AUTODEBIT'))]

In [ ]:
a

       Trans.ID             Trans.Date  ... Customer Mobile Number     source
7     118683391  28/02/2022 11:31:21PM  ...                    NaN  AUTODEBIT
8     118683143  28/02/2022 11:17:46PM  ...                    NaN  AUTODEBIT
9     118682640  28/02/2022 10:55:52PM  ...                    NaN  AUTODEBIT
10    118682479  28/02/2022 10:51:19PM  ...                    NaN  AUTODEBIT
11    118682124  28/02/2022 10:39:15PM  ...                    NaN  AUTODEBIT
...         ...                    ...  ...                    ...        ...
7330  115075760  01/02/2022 12:02:38AM  ...                    NaN  AUTODEBIT
7331  115075750  01/02/2022 12:02:08AM  ...                    NaN  AUTODEBIT
7332  115075738  01/02/2022 12:01:38AM  ...                    NaN  AUTODEBIT
7333  115075733  01/02/2022 12:01:23AM  ...                    NaN  AUTODEBIT
7334  115075709  01/02/2022 12:00:24AM  ...                    NaN  AUTODEBIT

[5712 rows x 30 columns]

In [ ]:
a['Net to Merchant'].sum()

82699.37

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5712 entries, 7 to 7334
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Trans.ID                    5712 non-null   int64
 1   Trans.Date                  5712 non-null   object
 2   Settlement Date             5712 non-null   object
 3   Value Date                  5712 non-null   object
 4   Interpay Ref No             5712 non-null   int64
 5   Fee Type                    5712 non-null   object
 6   Invoice Amount              5712 non-null   float64
 7   Invoice Currency            5712 non-null   object
 8   Transacted Amount           5712 non-null   float64
 9   Transacted Currency         5712 non-null   object
 10  Commission Amount           5712 non-null   float64
 11  Net to Merchant             5712 non-null   float64
 12  Payee Name                  5712 non-null   object
 13  Mobile                      5712 non-null   int64
 14  Payee Email                 5712 non-null   object
 15  Merchant Ref.Code           5712 non-null   object
 16  Merchant-Client Code        0 non-null      float64
 17  Transaction Type            5712 non-null   object
 18  Payment Mode Name           5712 non-null   object
 19  Payment Mode Reference      5712 non-null   object
 20  Bank Name                   5712 non-null   object
 21  Bank Account                5712 non-null   int64
 22  Transaction Source          5712 non-null   object
 23  Reversal Status             0 non-null      float64
 24  Reversal Date               0 non-null      float64
 25  Reversal Payback Amount     5712 non-null   int64
 26  Agent Reference Number      0 non-null      float64
 27  Customer Membership Number  0 non-null      float64
 28  Customer Mobile Number      0 non-null      float64
 29  source                      5712 non-null   object
dtypes: float64(10), int64(5), object(15)
memory usage: 1.4+ MB

In [ ]:
a1 = a.drop_duplicates(subset=['Mobile'], keep='first')

In [ ]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1192 entries, 7 to 7310
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Trans.ID                    1192 non-null   int64
 1   Trans.Date                  1192 non-null   object
 2   Settlement Date             1192 non-null   object
 3   Value Date                  1192 non-null   object
 4   Interpay Ref No             1192 non-null   int64
 5   Fee Type                    1192 non-null   object
 6   Invoice Amount              1192 non-null   float64
 7   Invoice Currency            1192 non-null   object
 8   Transacted Amount           1192 non-null   float64
 9   Transacted Currency         1192 non-null   object
 10  Commission Amount           1192 non-null   float64
 11  Net to Merchant             1192 non-null   float64
 12  Payee Name                  1192 non-null   object
 13  Mobile                      1192 non-null   int64
 14  Payee Email                 1192 non-null   object
 15  Merchant Ref.Code           1192 non-null   object
 16  Merchant-Client Code        0 non-null      float64
 17  Transaction Type            1192 non-null   object
 18  Payment Mode Name           1192 non-null   object
 19  Payment Mode Reference      1192 non-null   object
 20  Bank Name                   1192 non-null   object
 21  Bank Account                1192 non-null   int64
 22  Transaction Source          1192 non-null   object
 23  Reversal Status             0 non-null      float64
 24  Reversal Date               0 non-null      float64
 25  Reversal Payback Amount     1192 non-null   int64
 26  Agent Reference Number      0 non-null      float64
 27  Customer Membership Number  0 non-null      float64
 28  Customer Mobile Number      0 non-null      float64
 29  source                      1192 non-null   object
dtypes: float64(10), int64(5), object(15)
memory usage: 288.7+ KB

In [ ]:
a1

       Trans.ID             Trans.Date  ... Customer Mobile Number     source
7     118683391  28/02/2022 11:31:21PM  ...                    NaN  AUTODEBIT
8     118683143  28/02/2022 11:17:46PM  ...                    NaN  AUTODEBIT
9     118682640  28/02/2022 10:55:52PM  ...                    NaN  AUTODEBIT
10    118682479  28/02/2022 10:51:19PM  ...                    NaN  AUTODEBIT
11    118682124  28/02/2022 10:39:15PM  ...                    NaN  AUTODEBIT
...         ...                    ...  ...                    ...        ...
7284  115077030  01/02/2022 01:48:13AM  ...                    NaN  AUTODEBIT
7288  115076883  01/02/2022 01:29:54AM  ...                    NaN  AUTODEBIT
7298  115076577  01/02/2022 12:47:31AM  ...                    NaN  AUTODEBIT
7309  115076364  01/02/2022 12:35:18AM  ...                    NaN  AUTODEBIT
7310  115076354  01/02/2022 12:34:44AM  ...                    NaN  AUTODEBIT

[1192 rows x 30 columns]